library(ggplot2)
library(RColorBrewer)
library(gdata)
library(gtools) 
library(RgoogleMaps)
library(ggmap)   
library(dplyr)
library(car)
library(reports)
library(tidyr)
print("loaded from MacMon .Rprofile")
